# Generated by Django 3.1.7 on 2021-04-01 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yfcases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'yfcase_city',
            },
        ),
        migrations.AddField(
            model_name='yfcase',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.customuser', verbose_name='區域負責人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseBigSection',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='段號'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseCompany',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所屬公司'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseCreditor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='債權人'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDebtor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='債務人'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseOtherAddress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='其他住址'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseSmallSection',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='小段'),
        ),
        migrations.AlterModelTable(
            name='yfcase',
            table='yfcase_yfcase',
        ),
        migrations.CreateModel(
            name='Township',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yfcases.city')),
            ],
            options={
                'db_table': 'yfcase_township',
            },
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseCity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yfcases.city', verbose_name='縣市'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseTownship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yfcases.township', verbose_name='鄉鎮區里'),
        ),
    ]
