# Generated by Django 3.1.7 on 2021-04-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0002_auto_20210401_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yfcase',
            name='yfcaseOtherAddress',
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseAlley',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='弄'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseFloor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='樓(含之幾)'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseLane',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='巷'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseNeighbor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='鄰'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='號'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseSection',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='段'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseStatus',
            field=models.BooleanField(default=False, verbose_name='案件狀態'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseStreet',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='街路'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseVillage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='村里'),
        ),
    ]
