# Generated by Django 3.1.7 on 2021-04-06 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0007_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicklistOccupy', models.BooleanField(default=False, verbose_name='01.占用鄰地？')),
                ('clicklistEegister', models.BooleanField(default=False, verbose_name='02.無未保存登記建物？')),
                ('clicklistParkingSpace', models.BooleanField(default=False, verbose_name='03.停車位(機車/汽車)？')),
                ('clicklistManagementFee', models.BooleanField(default=False, verbose_name='04.積欠管理費？')),
                ('clicklistRent', models.BooleanField(default=False, verbose_name='05.出租/出借/佔用？')),
                ('clicklistLeak', models.BooleanField(default=False, verbose_name='06.無嚴重漏水現象？')),
                ('clicklistEasyParking', models.BooleanField(default=False, verbose_name='07.停車方便？')),
                ('clicklistRailway', models.BooleanField(default=False, verbose_name='08.鄰近捷運站/台鐵站？')),
                ('clicklistVegetableMarket', models.BooleanField(default=False, verbose_name='09.鄰近菜市場？')),
                ('clicklistSupermarket', models.BooleanField(default=False, verbose_name='10.鄰近大賣場？')),
                ('clicklistSchool', models.BooleanField(default=False, verbose_name='11.鄰近學校？')),
                ('clicklistPark', models.BooleanField(default=False, verbose_name='12.鄰近公園？')),
                ('clicklistPostOffice', models.BooleanField(default=False, verbose_name='13.鄰近郵局/機關？')),
                ('clicklistMainRoad', models.BooleanField(default=False, verbose_name='14.鄰近幹道？')),
                ('clicklistWaterAndPowerFailure', models.BooleanField(default=False, verbose_name='15.斷水斷電？')),
                ('clicklistGoodVision', models.BooleanField(default=False, verbose_name='16.採光視野良好？')),
                ('yfcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicklists', to='yfcases.yfcase')),
            ],
        ),
    ]
